In [1]:
#Ridge reg(L2), Lasso reg(L1) [Regularization] -- to over come from the overfit in regression


In [2]:
x = {"s.no":[1,2,3], "Name":["x","y","z"]}
import pandas as pd
df = pd.DataFrame(x)
df

s.no Name
0     1    x
1     2    y
2     3    z

In [3]:
#Generate an even number 20 to 40 and odd number 60 to 100 and store in dataframe

In [4]:
even =0
odd = 0
for i in range(20,60,2):
        even += 1 #Count of even numbers
        print(i,end=" ")
for i in range(61,100,2):
    odd += 1# count of odd numbers
    print(i, end=' ')

20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99 

In [5]:
even

20

In [6]:
odd

20

In [7]:
Even = [i for i in range(20,60,2)]
Odd = [i for i in range(61,100,2)]

In [8]:
print(Even,end=" ")

[20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58] 

In [9]:
print(Odd,end=" ")

[61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99] 

In [10]:
df = pd.DataFrame({"Even":Even, "Odd": Odd}, index = [i for i in range(150,170)])

In [11]:
df

Even  Odd
150    20   61
151    22   63
152    24   65
153    26   67
154    28   69
155    30   71
156    32   73
157    34   75
158    36   77
159    38   79
160    40   81
161    42   83
162    44   85
163    46   87
164    48   89
165    50   91
166    52   93
167    54   95
168    56   97
169    58   99

In [12]:
df.iloc[2:5]

Even  Odd
152    24   65
153    26   67
154    28   69

In [13]:
df.loc[152:154]

Even  Odd
152    24   65
153    26   67
154    28   69

In [14]:
#Sort this dataframe by even number in descending order

In [15]:
df.sort_values(by=["Odd"], ascending=False)

Even  Odd
169    58   99
168    56   97
167    54   95
166    52   93
165    50   91
164    48   89
163    46   87
162    44   85
161    42   83
160    40   81
159    38   79
158    36   77
157    34   75
156    32   73
155    30   71
154    28   69
153    26   67
152    24   65
151    22   63
150    20   61

In [16]:
df1 = pd.read_csv(r"https://raw.githubusercontent.com/singhrau0/Big-Data-Preprocessing/main/titanic_dataset.csv")

In [17]:
df1_copy = df1.copy()

In [18]:
df1_copy

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [19]:
#female data who survived
df1[(df1['Gender']=='female') & (df1['Survived'] == 1)]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
874          875         1       2   
875          876         1       3   
879          880         1       1   
880          881         1       2   
887          888         1       1   

                                                  Name  Gender   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
874              Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0      1   
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
874      0         P/PP 3381  24.0000   NaN        C  
875      0              2667   7.2250   NaN        C  
879      1             11767  83.1583   C50        C  
880      1            230433  26.0000   NaN        S  
887      0            112053  30.0000   B42        S  

[233 rows x 12 columns]

In [20]:
#Increase the price of fare by 50dollar  for those male data who survived
df1[(df1['Gender'] == 'male') & (df1['Survived'] == 1)]['Fare']+50

17      63.0000
21      63.0000
23      85.5000
36      57.2292
55      85.5000
         ...   
838    106.4958
839     79.7000
857     76.5500
869     61.1333
889     80.0000
Name: Fare, Length: 109, dtype: float64

In [21]:
#update in real data 
df1

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [22]:
df1.loc[(df1['Gender'] == 'male') & (df1['Survived'] == 1), ['Fare']] = df1[(df1['Gender'] == 'male') & (df1['Survived'] == 1)]

In [23]:
df1

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [24]:
df1.loc[df1['Gender'] == 'male',['Gender']] = "men"

In [25]:
df1

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris     men  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry     men  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas     men  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell     men  26.0      0   
890                                Dooley, Mr. Patrick     men  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [26]:
#Fetch data fare>100 and update embark by new
df1.loc[df1['Fare']>100, ['Embarked']] = "New" 

In [27]:
df1['Embarked'].value_counts()

S      620
C      139
Q       77
New     53
Name: Embarked, dtype: int64

In [28]:
df1

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris     men  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry     men  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas     men  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell     men  26.0      0   
890                                Dooley, Mr. Patrick     men  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [29]:
# pclass = 1, gender = female,then update age = 45.6
df1.loc[(df1['Pclass'] == 1) & (df1['Gender'] == 'female'), "Age"] = 45.6

In [30]:
df1

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris     men  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  45.6      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  45.6      1   
4                             Allen, Mr. William Henry     men  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas     men  27.0      0   
887                       Graham, Miss. Margaret Edith  female  45.6      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell     men  26.0      0   
890                                Dooley, Mr. Patrick     men  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [31]:
#fill null values in age column with median of the age column
df1.loc[df1['Age'].isnull(),['Age']] = df1['Age'].median()

In [32]:
df1.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [33]:
#Create a function take number from user that number should div by 2 and 4 but not with 6
def my_fun(x):
    if x%2 ==0 and x%4 == 0 and x%6!=0:
        print(f"{x} is divisable by 2 and 4 but not with 6")
    else:
        print("False")

my_fun(8985298)


False


In [34]:
x = (1,2,4,6, "hello", [9,0,7], 8.6 )

In [35]:
x

(1, 2, 4, 6, 'hello', [9, 0, 7], 8.6)

In [36]:
x[5][0] = 407

In [37]:
x

(1, 2, 4, 6, 'hello', [407, 0, 7], 8.6)

In [38]:
y = [4,5,(40,30),9]

In [39]:
y

[4, 5, (40, 30), 9]

In [40]:
y[2][1] = 100

TypeError: 'tuple' object does not support item assignment

In [41]:
# diff btw numpy array and list
#Numpy holds homogeneous data but list can hold can hold multiple datatype (Heterogeneous)

import numpy as np

In [42]:
type(np.array([1,2,34,5,6,7,"hello","new", 50.6]))

numpy.ndarray

In [43]:
np

<module 'numpy' from 'C:\\Users\\HP\\anaconda3\\navigator\\lib\\site-packages\\numpy\\__init__.py'>

In [44]:
pd

<module 'pandas' from 'C:\\Users\\HP\\anaconda3\\navigator\\lib\\site-packages\\pandas\\__init__.py'>

In [45]:
a = np.array([2,3,4,5])

In [46]:
b = np.array([1,2,3,4])

In [47]:
a+b

array([3, 5, 7, 9])

In [48]:
a*b

array([ 2,  6, 12, 20])

In [49]:
a//b

array([2, 1, 1, 1], dtype=int32)

In [50]:
a%b

array([0, 1, 1, 1], dtype=int32)

In [ ]:
a = np.random.randint(10, size=(3,3))

In [ ]:
a.ndim

In [ ]:
a.T

In [ ]:
a

In [2]:
#convert one dim to two
import numpy as np
gt = np.random.randint(20, size=10)

In [3]:
gt

array([ 8, 18, 16,  8,  3,  0, 18,  4, 11, 11])

In [8]:
gt1 = gt.reshape(5,2)
gt1

array([[ 8, 18],
       [16,  8],
       [ 3,  0],
       [18,  4],
       [11, 11]])

In [6]:
gt1.ndim

2

In [9]:
#array size 8 of random then rshape with 2 dim woth all possibility
arr = np.random.randint(10, size=8)

In [14]:
arr.reshape(-1,1).ndim

2

In [11]:
arr.reshape(4,2)

array([[5, 1],
       [6, 2],
       [4, 7],
       [5, 2]])

In [ ]:
arr.reshape(1,8)

In [ ]:
arr.reshape(8,1)

In [ ]:
arr.reshape(1,8)

In [ ]:
arr.reshape(2,4,1)

In [ ]:
#Create a fun take number from user check even or not
def my_fun(x):
    if x%2==0:
        print(f"{x} is Even")
    else:
        print(f"{x} is Odd")

In [ ]:
my_fun(5)

In [ ]:
#Take string check palindrone or not
x = input()
y = ""
for i in x:
    y = i+y
    
if y == x:
    print("palindrone")
else:
    print("Not a Palindrone")
    

In [ ]:
#Another method
def palindrone(x):
    if x.lower() == x[::-1].lower():
        print("Palindrone")
    else:
        print("Not a Palindrone")

In [ ]:
palindrone("racecar")

In [ ]:
#Prime Numbers in Range
count1 = 0
for x in range(100,200):
    count = 0
    for i in range(1,x+1):
        if x%i==0:
            count = count+1
    if count == 2:
        count1 = count1+1
        print(x,end=' ')
print("Number of Prime Numbers are",count1)

In [ ]:
x = int(input())
count = 0
for i in range(1,x+1):
    if x%i == 0:
        count = count+1
    
if count == 2:
    print("Prime")
else:
    print("Not Prime")

In [ ]:
#Lambda Func
ak = lambda x,y,z:x+y+z

In [ ]:
ak(10,20,30)

In [ ]:
#Squaring
sq = lambda x:x**2

In [ ]:
sq(4)

In [ ]:
a = [10,20,30,40]
b = [50,60,70,80]
c = [1,2,3,4]


In [ ]:
#MAP fun
list(map(ak,a,b)) #here ak expecting 3 values

In [ ]:
list(map(ak,a,b,c)) #here ak expecting 3 values

In [ ]:
e = [5,10,15,25]
list(map(sq,e))#Mapping all the values with lambda function

In [ ]:
#create a lambda fun that will take two values x,y then add x^2 + y^2
sqr = lambda x,y:x**2+y**2

In [ ]:
sqr(2,3)

In [ ]:
list(map(sqr,[4],[5]))

In [ ]:
list(map(sqr,[1,2,3],[1,2,3]))

In [ ]:
tuple(map(sqr,[1,2,3],[1,2,3]))

In [ ]:
set(list(map(sqr,[1,2,3],[1,2,3])))

In [ ]:
# create fun take single num from user then return num which is multiply of 100
def my_fun(x):
    return x*100

In [ ]:
my_fun(9)

In [ ]:
#map not only works with lambda but also with in built-fun, noral fun
set(map(my_fun,[4,5,6,7,8]))

In [ ]:
#create lambda check wheather even or not
even = lambda x:x%2==0

In [ ]:
even(424)

In [ ]:
 even1 = [10,20,31,32,24,35]

In [ ]:
list(map(even,even1))

In [ ]:
#Filter Function
list(filter(even, even1))

In [ ]:
#Reduce
from functools import reduce

In [ ]:
mul = lambda x,y:x*y

In [ ]:
reduce(mul,[1,2,3,4,5])

In [ ]:
#addition of even, odd from 10 to 20 
for i in range(10,21,2):
    
    print(i)

In [ ]:
#List Comprehension
[i for i in range(10,20) if i%2!=0]

In [ ]:
[i for i in range(10,20) if i%2==0]

In [ ]:
list(map(lambda a,b:a**2+b**2,[i for i in range(10,20) if i%2!=0] , [i for i in range(10,20) if i%2==0]))

In [ ]:
#Exceptional Handling/Error Handling
x = "j3klk34j34hk1"
su = 0
for i in x:
    try:
        su = su+int(i)
    except: 
        pass

In [ ]:
su

In [ ]:
h = "Hello"
try:
    h = int(h)
except:
    print("Except block")

In [ ]:
ok = "hii 34982 jsdkj"
sum = 0
for i in ok:
    try:
        sum = sum+1
    except:
        print("except block")
        
sum

In [ ]:
list1 = [1,2,3,"hello",(34,5),"hii"]
sum = 0
for i in list1:
    try:
        sum = sum+int(i)
    except:
        pass
sum

In [ ]:
#create *args function that user can pass anything then add 
def arg(*args):
    sum = 0
    for i in args:
        try:
            sum = sum+int(i)
        except:
            pass
    print(sum)
    
arg("Hii", 2,3,"hello")
   

In [ ]:
5/0

In [ ]:
try:
    d = 5/0
except Exception as e:
    print(e)

In [ ]:
try:
    45+"hello"
except Exception as e:
    print(e)

In [ ]:
#Create a fun take two values x,y then do x^2,y^2 if i get string msg then print unsupported
def my_fun(x,y):
    return x**2,y**2
try:
    my_fun("hii",3)
except:
    print("Unsupported ")

In [ ]:
my_fun(2,3)

In [ ]:
x = "h123pq29rst7p89"
for i in x:
    if i==type(int):
        print()